import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from "react";
import { useAuditLogs, useLoginLogs } from "./api";
// 日志管理屏（SC-4，只读）。七态：加载/错误/空/无权限/缺失/只读/成功。
export function SysLogPage({ roles }) {
    const canRead = roles.includes("管理员") || roles.includes("审计员"); // sys:log:read
    const [tab, setTab] = useState("audit");
    const audit = useAuditLogs({});
    const loginLogs = useLoginLogs({});
    if (!canRead) {
        return _jsx("p", { className: "p-6 text-amber-700", role: "alert", children: "\u65E0\u8BBF\u95EE\u65E5\u5FD7\u7684\u6743\u9650\u3002" });
    }
    const active = tab === "audit" ? audit : loginLogs;
    return (_jsxs("div", { className: "space-y-4 p-6", children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsx("h1", { className: "text-xl font-semibold", children: "\u65E5\u5FD7\u7BA1\u7406" }), _jsx("button", { className: tab === "audit" ? "font-semibold underline" : "text-gray-600", onClick: () => setTab("audit"), children: "\u64CD\u4F5C\u65E5\u5FD7" }), _jsx("button", { className: tab === "login" ? "font-semibold underline" : "text-gray-600", onClick: () => setTab("login"), children: "\u767B\u5F55\u65E5\u5FD7" })] }), active.isLoading && _jsx("p", { children: "\u52A0\u8F7D\u4E2D\u2026" }), active.isError && (_jsxs("div", { role: "alert", className: "text-red-600", children: ["\u52A0\u8F7D\u5931\u8D25\u3002", _jsx("button", { className: "underline", onClick: () => active.refetch(), children: "\u91CD\u8BD5" })] })), active.data && active.data.length === 0 && _jsx("p", { className: "text-gray-500", children: "\u6682\u65E0\u65E5\u5FD7\u3002" }), tab === "audit" && audit.data && audit.data.length > 0 && (_jsxs("table", { className: "w-full border-collapse text-sm", children: [_jsx("thead", { children: _jsxs("tr", { className: "border-b text-left", children: [_jsx("th", { className: "p-2", children: "\u65F6\u95F4" }), _jsx("th", { className: "p-2", children: "\u64CD\u4F5C\u4EBA" }), _jsx("th", { className: "p-2", children: "\u52A8\u4F5C" }), _jsx("th", { className: "p-2", children: "\u5B9E\u4F53" })] }) }), _jsx("tbody", { children: audit.data.map((r) => (_jsxs("tr", { className: "border-b", children: [_jsx("td", { className: "p-2", children: r.ts }), _jsx("td", { className: "p-2", children: r.actor }), _jsx("td", { className: "p-2", children: r.action }), _jsx("td", { className: "p-2", children: r.entity_id })] }, r.id))) })] })), tab === "login" && loginLogs.data && loginLogs.data.length > 0 && (_jsxs("table", { className: "w-full border-collapse text-sm", children: [_jsx("thead", { children: _jsxs("tr", { className: "border-b text-left", children: [_jsx("th", { className: "p-2", children: "\u65F6\u95F4" }), _jsx("th", { className: "p-2", children: "\u7528\u6237\u540D" }), _jsx("th", { className: "p-2", children: "\u7ED3\u679C" }), _jsx("th", { className: "p-2", children: "\u8BE6\u60C5" })] }) }), _jsx("tbody", { children: loginLogs.data.map((r) => (_jsxs("tr", { className: "border-b", children: [_jsx("td", { className: "p-2", children: r.ts }), _jsx("td", { className: "p-2", children: r.username }), _jsx("td", { className: "p-2", children: r.success ? "成功" : "失败" }), _jsx("td", { className: "p-2", children: r.detail || "—" })] }, r.id))) })] }))] }));
}
