/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutDashboardRouteImport } from './routes/_layout/dashboard'
import { Route as LayoutSystemUsersRouteImport } from './routes/_layout/system/users'
import { Route as LayoutSystemRolesRouteImport } from './routes/_layout/system/roles'
import { Route as LayoutSystemMenusRouteImport } from './routes/_layout/system/menus'
import { Route as LayoutSystemLogsRouteImport } from './routes/_layout/system/logs'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDashboardRoute = LayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSystemUsersRoute = LayoutSystemUsersRouteImport.update({
  id: '/system/users',
  path: '/system/users',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSystemRolesRoute = LayoutSystemRolesRouteImport.update({
  id: '/system/roles',
  path: '/system/roles',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSystemMenusRoute = LayoutSystemMenusRouteImport.update({
  id: '/system/menus',
  path: '/system/menus',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSystemLogsRoute = LayoutSystemLogsRouteImport.update({
  id: '/system/logs',
  path: '/system/logs',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/settings': typeof LayoutSettingsRoute
  '/system/logs': typeof LayoutSystemLogsRoute
  '/system/menus': typeof LayoutSystemMenusRoute
  '/system/roles': typeof LayoutSystemRolesRoute
  '/system/users': typeof LayoutSystemUsersRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/system/logs': typeof LayoutSystemLogsRoute
  '/system/menus': typeof LayoutSystemMenusRoute
  '/system/roles': typeof LayoutSystemRolesRoute
  '/system/users': typeof LayoutSystemUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/_layout/dashboard': typeof LayoutDashboardRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/system/logs': typeof LayoutSystemLogsRoute
  '/_layout/system/menus': typeof LayoutSystemMenusRoute
  '/_layout/system/roles': typeof LayoutSystemRolesRoute
  '/_layout/system/users': typeof LayoutSystemUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/settings'
    | '/system/logs'
    | '/system/menus'
    | '/system/roles'
    | '/system/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/dashboard'
    | '/settings'
    | '/'
    | '/system/logs'
    | '/system/menus'
    | '/system/roles'
    | '/system/users'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/_layout/dashboard'
    | '/_layout/settings'
    | '/_layout/'
    | '/_layout/system/logs'
    | '/_layout/system/menus'
    | '/_layout/system/roles'
    | '/_layout/system/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dashboard': {
      id: '/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutDashboardRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/system/users': {
      id: '/_layout/system/users'
      path: '/system/users'
      fullPath: '/system/users'
      preLoaderRoute: typeof LayoutSystemUsersRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/system/roles': {
      id: '/_layout/system/roles'
      path: '/system/roles'
      fullPath: '/system/roles'
      preLoaderRoute: typeof LayoutSystemRolesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/system/menus': {
      id: '/_layout/system/menus'
      path: '/system/menus'
      fullPath: '/system/menus'
      preLoaderRoute: typeof LayoutSystemMenusRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/system/logs': {
      id: '/_layout/system/logs'
      path: '/system/logs'
      fullPath: '/system/logs'
      preLoaderRoute: typeof LayoutSystemLogsRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutDashboardRoute: typeof LayoutDashboardRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutSystemLogsRoute: typeof LayoutSystemLogsRoute
  LayoutSystemMenusRoute: typeof LayoutSystemMenusRoute
  LayoutSystemRolesRoute: typeof LayoutSystemRolesRoute
  LayoutSystemUsersRoute: typeof LayoutSystemUsersRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutDashboardRoute: LayoutDashboardRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutSystemLogsRoute: LayoutSystemLogsRoute,
  LayoutSystemMenusRoute: LayoutSystemMenusRoute,
  LayoutSystemRolesRoute: LayoutSystemRolesRoute,
  LayoutSystemUsersRoute: LayoutSystemUsersRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
