"""init

Revision ID: 1ec8b01338f7
Revises: 
Create Date: 2026-06-23 19:55:48.642568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1ec8b01338f7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('ip', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=True),
    sa.Column('browser', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('os', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('fail_reason', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_log_username'), 'login_log', ['username'], unique=False)
    op.create_table('menu',
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('menu_type', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('permission', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('component', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('visible', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['menu.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operation_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('module', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('method', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('ip', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=True),
    sa.Column('request_params', sa.Text(), nullable=True),
    sa.Column('response_code', sa.Integer(), nullable=True),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('cost_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('data_scope', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('remark', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_code'), 'role', ['code'], unique=True)
    op.create_table('user',
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('real_name', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('avatar', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('is_superadmin', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('login_fail_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_ip', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('role_menu',
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('menu_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['menu_id'], ['menu.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'menu_id')
    )
    op.create_table('user_role',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_role')
    op.drop_table('role_menu')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_role_code'), table_name='role')
    op.drop_table('role')
    op.drop_table('operation_log')
    op.drop_table('menu')
    op.drop_index(op.f('ix_login_log_username'), table_name='login_log')
    op.drop_table('login_log')
    # ### end Alembic commands ###
